name: Main Workflow

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job principal ejecutándose..."

  trigger-logs:
    needs: build
    uses:  IsaacCanache/pipelines/.github/workflows/logs.yaml@1b5997c6a03706d7d0e511bb4c7aad7c2eda4e26
    with:
        run_id: ${{ github.run_id }}
        repositorio: ${{ github.repository }}




