name: Main Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job principal ejecutándose..."

  trigger-logs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Disparar workflow de logs en otro repo vía API
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/IsaacCanache/pipelines/actions/workflows/logs.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"run_id\":\"${{ github.run_id }}\",\"repositorio\":\"${{ github.repository }}\"}}"


