name: Main Workflow

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job principal ejecutándose..."

  trigger-logs:
    needs: build
    uses: IsaacCanache/pipelines/.github/workflows/logs.yml@cb382d3c992f84ffb1b1a3a8bb20cd14cb97749b
    with:
      run_id: ${{ github.run_id }}
      repositorio: ${{ github.repository }}



